---
- name: Reboot machine and send a message
  hosts: "{{ vm_name }}"
  become: true
  gather_facts: true

  tasks:
    -name: Reboot and send a message
     reboot:
       msg: "Rebooting machine in 5 seconds"
